### ISSUE TITLE
One-shot modifier keys do not light up when activated by other physical keys

### ISSUE THREAD

**Issue by indirect** [keyboardio/Kaleidoscope-LED-ActiveModColor#7] opened 2017-10-19 07:30 UTC
While setting up my keyboard, I've been experimenting with one-shot modifiers (thank you, by the way!). After adding this plugin, I noticed that my Hyper key (which I assigned to the physical `any` key) would cause the `cmd`, `shift`, `alt`, and `ctrl` keys to all light up anytime the `hyper` key was held down. However, once I changed the thumb-keys to be oneshots, they stopped lighting up when the `hyper` key was pressed

I checked on my computer, and the model01 is actually sending all four modifiers to the computer, but it doesn't light them up. Here's some code to illustrate what I mean.

When I use this code, pressing the hyper key causes the thumbkeys for ctrl, gui, and shift to light up:

```
#define Key_Hyper LALT(LCTRL(LGUI(Key_LeftShift)))
// Later on, in the keymap…
Key_LeftControl, Key_Backspace, Key_LeftGui, Key_LeftShift,
```

Defining the thumb keys this way, on the other hand, makes them start working as oneshot keys, but stop lighting up when the hyper key is pressed:

```
OSM(LeftControl), Key_Backspace, OSM(LeftGui), OSM(LeftShift),
```

Is this intentional? Am I using it wrong somehow? Just in case it's helpful, here is [my full firmware](https://gist.github.com/d5f3ab1f82d3a74c085c73c2b76f74a7). Thanks!

**Comment by algernon** [comment] 2017-10-19 07:51
My gut feeling is that the reason for this is because the code isn't prepared for keys like `Hyper`, keys that are a combination of other modifiers. What you see is not intended behaviour.

I *think* I know how to fix it, will try to find some time soon to do so. Thank you for the detailed report and reproduction steps!

**Comment by algernon** [comment] 2017-11-24 16:20
Right. I had a look at the code, and unfortunately, it is not possible to light up the OneShots when `Hyper` is pressed. Reason for this is that Kaleidoscope reuses the same flag bits for modifiers held with the key (the `LALT` & friends stuff) and for other things, and I can't tell the two apart. If I modify the code to light up when these bits are set, it will **also** light up for unrelated things.

There is one workaround I might recommend: using a Macro for `Hyper`, that also lights up the OneShot keys, something along these lines:

```c++
const macro_t *Hyper(uint8_t key_state) {
  if (keyIsPressed(key_state)) {
    LEDControl.setCrgbAt(0, 7, ActiveModColorEffect.highlight_color);
    LEDControl.setCrgbAt(2, 7, ActiveModColorEffect.highlight_color);
    LEDControl.setCrgbAt(3, 7, ActiveModColorEffect.highlight_color);
    LEDControl.setCrgbAt(3, 6, ActiveModColorEffect.highlight_color);
    return MACRO(D(LeftAlt), D(LeftControl), D(LeftGui), D(LeftShift));
  } else if (keyToggledOff(keyState)) {
    LEDControl.refreshAt(0, 7);
    LEDControl.refreshAt(2, 7);
    LEDControl.refreshAt(3, 7);
    LEDControl.refreshAt(3, 6);
  }

  return MACRO_NONE;
}
```

Adjust the coordinates as needed, and use use a macro instead of the current `Key_Hyper`.

**Comment by algernon** [comment] 2017-11-24 16:21
(And as the issue is not fixable as explained above, I'm closing it)

**Closed by algernon** 2017-11-24 16:21 UTC
Labels: bug, wontfix
